package io.github.yokigroup.view.notification;

/**
 * Generates event strings from notifications adopting the Visitor design pattern.
 */
public interface NotificationVisitor {
    /**
     * @param notification to generate the event string of.
     * @return the event string generated by the visitor
     */
    String getLevelUpNotificationText(LevelUpNotification notification);
    /**
     * @param notification to generate the event string of.
     * @return the event string generated by the visitor
     */
    String getNewYokimonNotificationText(NewYokimonNotification notification);
    /**
     * @param notification to generate the event string of.
     * @return the event string generated by the visitor
     */
    String getDeathNotificationText(DeathNotification notification);
    /**
     * @param notification to generate the event string of.
     * @return the event string generated by the visitor
     */
    String getSelectedAttackNotiticationText(AttackSelectedNotification notification);
    /**
     * @param notification to generate the event string of.
     * @return the event string generated by the visitor
     */
    String getAttackOutcomeNotificationText(AttackOutcomeNotification notification);
}
